# Generated by Django 5.2.17 on 2026-09-05 23:26

import apps.surveys.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impact', '0001_initial'),
        ('organisations', '0001_initial'),
        ('participants', '0001_initial'),
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('BASELINE', 'Baseline'), ('MIDLINE', 'Midline / Monitoring'), ('ENDLINE', 'Endline'), ('FOLLOW_UP', 'Follow-up'), ('CUSTOM', 'Custom')], default='BASELINE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('public_token', models.CharField(db_index=True, default=apps.surveys.models.generate_public_token, max_length=64, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('allow_multiple_responses', models.BooleanField(default=False, help_text='Allow more than one response per person.')),
                ('thank_you_message', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('impact_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='impact.impactproject')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='programmes.programme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('question_type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('NUMBER', 'Number'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('CHECKBOX', 'Checkboxes'), ('DROPDOWN', 'Dropdown'), ('YES_NO', 'Yes / No'), ('RATING_SCALE', 'Rating Scale (1-5)'), ('DATE', 'Date')], max_length=30)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255)),
                ('respondent_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted')], db_index=True, default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('impact_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='impact.impactproject')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='participants.participant')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='programmes.programme')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['organisation', 'status'], name='surveys_sur_organis_aaa683_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['organisation', 'programme'], name='surveys_sur_organis_bf86f9_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['organisation', 'public_token'], name='surveys_sur_organis_a99eb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyquestion',
            unique_together={('survey', 'order')},
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['organisation', 'survey', 'submitted_at'], name='surveys_sur_organis_bf6f28_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['organisation', 'created_at'], name='surveys_sur_organis_24aabc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('response', 'question')},
        ),
    ]
