# Generated by Django 5.2.14 on 2026-09-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ussd", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ussdsession",
            new_name="ussd_ussdse_phone_n_90aecd_idx",
            old_name="ussd_ussdse_phone_n_1f1e50_idx",
        ),
    ]
