# Generated by Django 5.2.17 on 2026-09-05 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impact', '0001_initial'),
        ('organisations', '0001_initial'),
        ('programmes', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmeasurement',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_measurements', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='impactproject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactproject',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='impactmeasurement',
            name='impact_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_measurements', to='impact.impactproject'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='impact_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='impact.impactproject'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='impactmeasurement',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='impact.kpi'),
        ),
        migrations.AddIndex(
            model_name='impactproject',
            index=models.Index(fields=['organisation', 'status'], name='impact_impa_organis_b15b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['organisation', 'programme'], name='impact_kpi_organis_7cc0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='impactmeasurement',
            index=models.Index(fields=['organisation', 'period'], name='impact_impa_organis_86bfcc_idx'),
        ),
    ]
