# Generated by Django 5.2.17 on 2026-09-05 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NON_BINARY', 'Non-binary'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED_OUT', 'Dropped Out')], db_index=True, default='REGISTERED', max_length=20)),
                ('enrolled_date', models.DateField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='programmes.programme')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='participant_organis_1412b8_idx'), models.Index(fields=['organisation', 'programme'], name='participant_organis_ac658b_idx'), models.Index(fields=['organisation', 'created_at'], name='participant_organis_48bfb8_idx')],
            },
        ),
    ]
