# Generated by Django 5.2.14 on 2026-09-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("NGO", "Non-Governmental Organisation"),
                            ("FOUNDATION", "Foundation"),
                            ("SCHOOL", "School / Training Institution"),
                            ("CORPORATE", "Corporate / CSR"),
                            ("COMMUNITY_BASED", "Community Based Organisation"),
                            ("GOVERNMENT", "Government"),
                            ("OTHER", "Other"),
                        ],
                        default="NGO",
                        max_length=30,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Uganda", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
