# Generated by Django 5.2.17 on 2026-09-05 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organisation_type', models.CharField(choices=[('NGO', 'Non-Governmental Organisation'), ('FOUNDATION', 'Foundation / Philanthropy'), ('TRAINING_INSTITUTE', 'Training Institution'), ('SCHOOL', 'School / Education'), ('COMMUNITY', 'Community Organisation'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='NGO', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
