import React, { useMemo, useState } from 'react';
import { ArrowRight, BarChart3, BriefcaseBusiness, CalendarDays, Check, ChevronRight, Filter, LayoutDashboard, MapPin, Plus, Search, Settings2, Sparkles, Target, TrendingUp, UserPlus, UsersRound, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

interface OrgWorkspaceProps { initialTab?: string; }
type WorkspaceTab = 'dashboard' | 'programmes' | 'participants' | 'applications' | 'analytics' | 'settings';
type CandidateStatus = 'Matched' | 'Invited' | 'Selected' | 'Rejected';

interface Candidate { id: string; name: string; location: string; skills: string; education: string; match: number; status: CandidateStatus; }
interface Programme { id: string; name: string; category: string; target: number; matched: number; applications: number; selected: number; status: 'Active' | 'Draft'; deadline: string; }

const seedProgrammes: Programme[] = [
  { id: 'p1', name: 'Digital Skills for Young Women', category: 'Skills', target: 180, matched: 142, applications: 96, selected: 38, status: 'Active', deadline: '20 Sep 2026' },
  { id: 'p2', name: 'Women in Tech Accelerator', category: 'Employment', target: 80, matched: 61, applications: 42, selected: 18, status: 'Active', deadline: '04 Oct 2026' },
  { id: 'p3', name: 'Future Founders Lab', category: 'Entrepreneurship', target: 50, matched: 0, applications: 0, selected: 0, status: 'Draft', deadline: '18 Oct 2026' }
];

const seedCandidates: Candidate[] = [
  { id: 'c1', name: 'Sarah Namukasa', location: 'Kampala', skills: 'React, JavaScript', education: 'Diploma', match: 94, status: 'Matched' },
  { id: 'c2', name: 'Amina K.', location: 'Gulu', skills: 'Python, Data', education: 'Degree', match: 91, status: 'Matched' },
  { id: 'c3', name: 'Grace N.', location: 'Jinja', skills: 'UI/UX, Figma', education: 'Diploma', match: 87, status: 'Invited' },
  { id: 'c4', name: 'Beatrice A.', location: 'Wakiso', skills: 'Digital marketing', education: 'Certificate', match: 84, status: 'Selected' },
  { id: 'c5', name: 'Janet O.', location: 'Mbale', skills: 'Excel, Research', education: 'Degree', match: 81, status: 'Matched' }
];

const tabFromInitial = (initialTab: string): WorkspaceTab => {
  if (initialTab === 'overview') return 'dashboard';
  if (initialTab === 'forms' || initialTab === 'monitoring' || initialTab === 'impact' || initialTab === 'reports') return 'analytics';
  if (initialTab === 'participants') return 'participants';
  if (initialTab === 'programmes') return 'programmes';
  return (initialTab as WorkspaceTab) || 'dashboard';
};

export const OrgWorkspace: React.FC<OrgWorkspaceProps> = ({ initialTab = 'overview' }) => {
  const [activeTab, setActiveTab] = useState<WorkspaceTab>(tabFromInitial(initialTab));
  const [programmes, setProgrammes] = useState(seedProgrammes);
  const [candidates, setCandidates] = useState(seedCandidates);
  const [candidateSearch, setCandidateSearch] = useState('');
  const [locationFilter, setLocationFilter] = useState('All locations');
  const [showCreate, setShowCreate] = useState(false);
  const [selectedCandidate, setSelectedCandidate] = useState<Candidate | null>(null);
  const [applicationFilter, setApplicationFilter] = useState<'All' | CandidateStatus>('All');
  const [newProgramme, setNewProgramme] = useState({ name: '', description: '', category: 'Skills', location: 'Kampala', target: '100', deadline: '' });

  const filteredCandidates = useMemo(() => candidates.filter((candidate) => {
    const query = candidateSearch.toLowerCase();
    const matchesSearch = !query || `${candidate.name} ${candidate.skills} ${candidate.education}`.toLowerCase().includes(query);
    const matchesLocation = locationFilter === 'All locations' || candidate.location === locationFilter;
    return matchesSearch && matchesLocation;
  }), [candidateSearch, candidates, locationFilter]);

  const updateCandidate = (id: string, status: CandidateStatus) => setCandidates((current) => current.map((candidate) => candidate.id === id ? { ...candidate, status } : candidate));
  const createProgramme = (event: React.FormEvent) => {
    event.preventDefault();
    setProgrammes((current) => [...current, { id: `p${Date.now()}`, name: newProgramme.name, category: newProgramme.category, target: Number(newProgramme.target) || 100, matched: 0, applications: 0, selected: 0, status: 'Draft', deadline: newProgramme.deadline || 'Not set' }]);
    setNewProgramme({ name: '', description: '', category: 'Skills', location: 'Kampala', target: '100', deadline: '' });
    setShowCreate(false);
    setActiveTab('programmes');
  };

  const navigation: Array<{ id: WorkspaceTab; label: string; icon: React.ElementType }> = [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { id: 'programmes', label: 'Programmes', icon: BriefcaseBusiness },
    { id: 'participants', label: 'Beneficiaries', icon: UsersRound },
    { id: 'applications', label: 'Applications', icon: UserPlus },
    { id: 'analytics', label: 'Analytics', icon: BarChart3 },
    { id: 'settings', label: 'Settings', icon: Settings2 }
  ];

  return <div className="org-workspace" id="org-workspace">
    <aside className="org-workspace__sidebar">
      <div><div className="org-workspace__brand"><span>VG</span><div><strong>Voice of a Girl</strong><small>Organisation workspace</small></div></div><div className="org-workspace__org"><span className="org-workspace__avatar">FA</span><div><strong>FemmeTech Africa</strong><small>Verified organisation</small></div></div><nav className="org-workspace__nav" aria-label="Organisation navigation">{navigation.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setActiveTab(id)} className={activeTab === id ? 'is-active' : ''}><Icon className="h-4 w-4" />{label}</button>)}</nav></div>
      <div className="org-workspace__sidebar-foot"><span className="org-workspace__status-dot" /> Demo workspace synced</div>
    </aside>
    <main className="org-workspace__main"><header className="org-workspace__topbar"><div><span className="org-workspace__crumb">Organisation workspace / {navigation.find((item) => item.id === activeTab)?.label}</span><h1>{activeTab === 'dashboard' ? 'Good morning, FemmeTech Africa' : navigation.find((item) => item.id === activeTab)?.label}</h1></div><div className="org-workspace__top-actions"><button className="org-workspace__icon-button" title="Notifications"><span>3</span>•</button><div className="org-workspace__user"><span>FA</span><small>FemmeTech Africa</small></div></div></header>
      {activeTab === 'dashboard' && <DashboardView programmes={programmes} onCreate={() => setShowCreate(true)} onNavigate={setActiveTab} />}
      {activeTab === 'programmes' && <ProgrammesView programmes={programmes} onCreate={() => setShowCreate(true)} onSelect={(id) => setActiveTab('participants')} />}
      {activeTab === 'participants' && <MatchesView candidates={filteredCandidates} search={candidateSearch} setSearch={setCandidateSearch} location={locationFilter} setLocation={setLocationFilter} onSelect={setSelectedCandidate} onUpdate={updateCandidate} />}
      {activeTab === 'applications' && <ApplicationsView candidates={candidates} filter={applicationFilter} setFilter={setApplicationFilter} onUpdate={updateCandidate} />}
      {activeTab === 'analytics' && <AnalyticsView />}
      {activeTab === 'settings' && <SettingsView />}
    </main>
    {showCreate && <CreateProgrammeModal form={newProgramme} setForm={setNewProgramme} onClose={() => setShowCreate(false)} onSubmit={createProgramme} />}
    {selectedCandidate && <CandidateModal candidate={selectedCandidate} onClose={() => setSelectedCandidate(null)} onInvite={() => { updateCandidate(selectedCandidate.id, 'Invited'); setSelectedCandidate(null); }} />}
  </div>;
};

function MetricCard({ label, value, detail, tone = '' }: { label: string; value: string; detail: string; tone?: string }) { return <div className={`org-metric-card ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }

function DashboardView({ programmes, onCreate, onNavigate }: { programmes: Programme[]; onCreate: () => void; onNavigate: (tab: WorkspaceTab) => void }) {
  return <section className="org-page"><div className="org-page__headline"><div><span className="org-kicker">Programme acquisition overview</span><p>Here is how your programmes are performing.</p></div><button className="org-primary-button" onClick={onCreate}><Plus className="h-4 w-4" /> Create Programme</button></div><div className="org-metric-grid"><MetricCard label="Active programmes" value={`${programmes.filter((p) => p.status === 'Active').length}`} detail="+1 this month" /><MetricCard label="Beneficiaries reached" value="4,280" detail="Across 24 districts" tone="is-blue" /><MetricCard label="Applications" value="940" detail="+18% this intake" tone="is-violet" /><MetricCard label="Selected" value="180" detail="84% of target" tone="is-green" /></div><section className="org-panel org-pipeline"><div className="org-panel__heading"><div><span className="org-kicker">Programme pipeline</span><h2>From reach to results</h2></div><button className="org-text-button" onClick={() => onNavigate('analytics')}>View analytics <ArrowRight className="h-3.5 w-3.5" /></button></div><div className="org-pipeline__steps">{[['Reached', '4,280'], ['Matched', '1,284'], ['Applied', '940'], ['Selected', '180']].map(([label, value], index) => <React.Fragment key={label}><div className="org-pipeline__step"><strong>{value}</strong><span>{label}</span></div>{index < 3 && <ChevronRight className="h-5 w-5" />}</React.Fragment>)}</div></section><section className="org-panel"><div className="org-panel__heading"><div><span className="org-kicker">Active programmes</span><h2>What your team is running</h2></div><button className="org-text-button" onClick={() => onNavigate('programmes')}>View all <ArrowRight className="h-3.5 w-3.5" /></button></div><div className="org-table-wrap"><table className="org-table"><thead><tr><th>Programme</th><th>Target</th><th>Matched</th><th>Applications</th><th>Selected</th><th>Status</th></tr></thead><tbody>{programmes.map((programme) => <tr key={programme.id}><td><strong>{programme.name}</strong><small>{programme.category} · {programme.deadline}</small></td><td>{programme.target}</td><td>{programme.matched}</td><td>{programme.applications}</td><td>{programme.selected}</td><td><span className={`org-status org-status--${programme.status.toLowerCase()}`}>{programme.status}</span></td></tr>)}</tbody></table></div></section><section className="org-panel org-activity"><div className="org-panel__heading"><div><span className="org-kicker">Recent activity</span><h2>Momentum this week</h2></div></div><div className="org-activity__grid"><div><strong>34</strong><span>new applications</span><small>Across 2 active programmes</small></div><div><strong>18</strong><span>candidates matched</span><small>Based on your criteria</small></div><div><strong>12</strong><span>candidates selected</span><small>Ready for onboarding</small></div></div></section></section>;
}

function ProgrammesView({ programmes, onCreate, onSelect }: { programmes: Programme[]; onCreate: () => void; onSelect: (id: string) => void }) { return <section className="org-page"><div className="org-page__headline"><div><span className="org-kicker">Programme management</span><p>Define who you need and let the platform surface the right people.</p></div><button className="org-primary-button" onClick={onCreate}><Plus className="h-4 w-4" /> Create Programme</button></div><div className="org-programme-grid">{programmes.map((programme) => <article className="org-programme-card" key={programme.id}><div className="org-programme-card__top"><span className="org-chip">{programme.category}</span><span className={`org-status org-status--${programme.status.toLowerCase()}`}>{programme.status}</span></div><h2>{programme.name}</h2><p>Find and support young women with the right skills, interests, and goals.</p><div className="org-programme-card__stats"><div><strong>{programme.target}</strong><span>Target</span></div><div><strong>{programme.matched}</strong><span>Matched</span></div><div><strong>{programme.selected}</strong><span>Selected</span></div></div><div className="org-programme-card__foot"><span><CalendarDays className="h-3.5 w-3.5" /> Deadline {programme.deadline}</span><button onClick={() => onSelect(programme.id)}>View programme <ArrowRight className="h-3.5 w-3.5" /></button></div></article>)}</div></section>; }

function MatchesView({ candidates, search, setSearch, location, setLocation, onSelect, onUpdate }: { candidates: Candidate[]; search: string; setSearch: (value: string) => void; location: string; setLocation: (value: string) => void; onSelect: (candidate: Candidate) => void; onUpdate: (id: string, status: CandidateStatus) => void }) { return <section className="org-page"><div className="org-page__headline"><div><span className="org-kicker">Matching engine</span><p>Based on the requirements of your programme.</p></div><span className="org-match-total"><Sparkles className="h-4 w-4" /> 1,284 potential matches</span></div><section className="org-panel org-matching-panel"><div className="org-matching-panel__intro"><Target className="h-5 w-5" /><div><strong>Find the right beneficiaries</strong><span>Organisations define who they need. Voice of a Girl makes the shortlist visible.</span></div></div><div className="org-filter-bar"><div className="org-search"><SearchIcon /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search candidates, skills, education..." /></div><select value={location} onChange={(e) => setLocation(e.target.value)}><option>All locations</option><option>Kampala</option><option>Gulu</option><option>Jinja</option><option>Wakiso</option><option>Mbale</option></select><button className="org-filter-button"><Filter className="h-3.5 w-3.5" /> Filters</button></div><div className="org-table-wrap"><table className="org-table org-table--matches"><thead><tr><th>Candidate</th><th>Location</th><th>Skills</th><th>Education</th><th>Match</th><th>Status</th><th /></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.id}><td><strong>{candidate.name}</strong><small>Profile completed 92%</small></td><td><MapPin className="inline h-3.5 w-3.5" /> {candidate.location}</td><td>{candidate.skills}</td><td>{candidate.education}</td><td><span className="org-match-score">{candidate.match}%</span></td><td><span className={`org-status org-status--${candidate.status.toLowerCase()}`}>{candidate.status}</span></td><td className="org-table__actions"><button onClick={() => onSelect(candidate)}>View</button>{candidate.status === 'Matched' && <button onClick={() => onUpdate(candidate.id, 'Invited')}>Invite</button>}</td></tr>)}</tbody></table></div></section></section>; }

function ApplicationsView({ candidates, filter, setFilter, onUpdate }: { candidates: Candidate[]; filter: 'All' | CandidateStatus; setFilter: (filter: 'All' | CandidateStatus) => void; onUpdate: (id: string, status: CandidateStatus) => void }) { const applications = candidates.filter((candidate) => candidate.status !== 'Matched'); return <section className="org-page"><div className="org-page__headline"><div><span className="org-kicker">Candidate decisions</span><p>Review applications and move the right people forward.</p></div></div><section className="org-panel"><div className="org-tabs">{(['All', 'Invited', 'Selected', 'Rejected'] as const).map((tab) => <button className={filter === tab ? 'is-active' : ''} onClick={() => setFilter(tab)} key={tab}>{tab === 'Invited' ? 'Reviewing' : tab}</button>)}</div><div className="org-table-wrap"><table className="org-table"><thead><tr><th>Applicant</th><th>Programme</th><th>Match</th><th>Applied</th><th>Status</th><th>Action</th></tr></thead><tbody>{applications.filter((candidate) => filter === 'All' || candidate.status === filter).map((candidate) => <tr key={candidate.id}><td><strong>{candidate.name}</strong><small>{candidate.location}</small></td><td>Digital Skills for Young Women</td><td><span className="org-match-score">{candidate.match}%</span></td><td>12 Sep 2026</td><td><span className={`org-status org-status--${candidate.status.toLowerCase()}`}>{candidate.status}</span></td><td className="org-table__actions"><button onClick={() => onUpdate(candidate.id, 'Selected')}><Check className="h-3.5 w-3.5" /> Select</button><button onClick={() => onUpdate(candidate.id, 'Rejected')}><X className="h-3.5 w-3.5" /> Reject</button></td></tr>)}</tbody></table></div>{applications.length === 0 && <EmptyState text="Applications will appear here as candidates respond to invitations." />}</section></section>; }

function AnalyticsView() { const funnel = [{ name: 'Reached', value: 4280 }, { name: 'Matched', value: 1284 }, { name: 'Applied', value: 940 }, { name: 'Selected', value: 180 }, { name: 'Completed', value: 148 }]; return <section className="org-page"><div className="org-page__headline"><div><span className="org-kicker">Programme results</span><p>Did we reach the right people, and what happened next?</p></div></div><div className="org-metric-grid"><MetricCard label="Reached" value="4,280" detail="24 districts" /><MetricCard label="Matched" value="1,284" detail="30% of reach" tone="is-blue" /><MetricCard label="Applied" value="940" detail="73% of matches" tone="is-violet" /><MetricCard label="Completed" value="148" detail="82% of selected" tone="is-green" /></div><section className="org-panel"><div className="org-panel__heading"><div><span className="org-kicker">Conversion funnel</span><h2>Reach → Match → Select → Complete</h2></div></div><div className="org-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel} layout="vertical" margin={{ left: 20, right: 28 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e8eaf0" /><XAxis type="number" hide /><YAxis type="category" dataKey="name" width={80} tick={{ fontSize: 12, fill: '#64748b' }} /><Tooltip /><Bar dataKey="value" fill="#6d4aff" radius={[0, 6, 6, 0]} barSize={28} /></BarChart></ResponsiveContainer></div></section><section className="org-panel"><div className="org-panel__heading"><div><span className="org-kicker">Measured outcomes</span><h2>Baseline versus endline</h2></div></div><div className="org-outcome-grid"><div><span>Digital skills</span><strong>32% <ArrowRight /> 81%</strong><small>Measured change: +49 points</small></div><div><span>Employment</span><strong>21% <ArrowRight /> 43%</strong><small>Measured change: +22 points</small></div><div><span>Confidence</span><strong>44% <ArrowRight /> 76%</strong><small>Measured change: +32 points</small></div></div></section></section>; }

function SettingsView() { return <section className="org-page"><div className="org-page__headline"><div><span className="org-kicker">Workspace settings</span><p>Manage your organisation profile and workspace preferences.</p></div></div><section className="org-panel"><h2>FemmeTech Africa Foundation</h2><p className="org-muted">Verified partner organisation · Kampala, Uganda</p><div className="org-settings-list"><div><strong>Organisation profile</strong><span>Contact details, programme defaults, and team identity</span></div><div><strong>Notifications</strong><span>Application, matching, and programme activity updates</span></div><div><strong>Data access</strong><span>Workspace access is managed by the Voice of a Girl team</span></div></div></section></section>; }

function CreateProgrammeModal({ form, setForm, onClose, onSubmit }: { form: any; setForm: (form: any) => void; onClose: () => void; onSubmit: (event: React.FormEvent) => void }) { return <div className="org-modal-backdrop"><form className="org-modal" onSubmit={onSubmit}><div className="org-modal__heading"><div><span className="org-kicker">New programme</span><h2>Create a Programme</h2></div><button type="button" onClick={onClose}><X className="h-5 w-5" /></button></div><p className="org-muted">Define the people you need. Matching starts with a clear brief.</p><div className="org-form-grid"><label>Programme name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. Women in Tech Accelerator" /></label><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>Education</option><option>Employment</option><option>Skills</option><option>Entrepreneurship</option><option>Other</option></select></label><label className="org-form-grid__wide">Description<textarea rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="What will this programme help participants achieve?" /></label><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Beneficiaries needed<input required type="number" min="1" value={form.target} onChange={(e) => setForm({ ...form, target: e.target.value })} /></label><label>Application deadline<input type="date" value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /></label></div><div className="org-modal__criteria"><span className="org-kicker">Who are you looking for?</span><div className="org-form-grid"><label>Age range<input placeholder="18–26" /></label><label>Education level<select><option>Any level</option><option>Secondary</option><option>Diploma</option><option>Degree</option></select></label><label>Skills<input placeholder="React, Python, Excel" /></label><label>Interests<input placeholder="Technology, business" /></label></div></div><div className="org-modal__actions"><button type="button" className="org-secondary-button" onClick={onClose}>Save Draft</button><button className="org-primary-button" type="submit">Publish Programme <ArrowRight className="h-4 w-4" /></button></div></form></div>; }

function CandidateModal({ candidate, onClose, onInvite }: { candidate: Candidate; onClose: () => void; onInvite: () => void }) { return <div className="org-modal-backdrop"><div className="org-modal org-modal--profile"><div className="org-modal__heading"><div><span className="org-kicker">Beneficiary profile</span><h2>{candidate.name}</h2></div><button onClick={onClose}><X className="h-5 w-5" /></button></div><div className="org-profile-score"><strong>{candidate.match}% Match</strong><span>Strong match based on skills, location, and education.</span></div><div className="org-profile-grid"><div><span>Location</span><strong>{candidate.location}</strong></div><div><span>Education</span><strong>{candidate.education}</strong></div><div><span>Skills</span><strong>{candidate.skills}</strong></div><div><span>Interests</span><strong>Technology · Leadership</strong></div></div><div className="org-modal__actions"><button className="org-secondary-button" onClick={onClose}>Close</button><button className="org-primary-button" onClick={onInvite}><UserPlus className="h-4 w-4" /> Invite to Programme</button></div></div></div>; }

function EmptyState({ text }: { text: string }) { return <div className="org-empty-state"><UsersRound className="h-7 w-7" /><p>{text}</p></div>; }
function SearchIcon() { return <Search className="h-4 w-4" />; }
