import { FormEvent, useEffect, useState } from 'react';
import { CheckCircle2, ClipboardList, Send } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../services/api';
import type { Form } from '../types';

const fallbackForm: Form = { id: 'public-survey', organisation_id: 'org_1', programme_id: 'prog_1', title: 'Participant progress check-in', description: 'Help our programme team understand your experience and the support you need.', form_type: 'MONITORING', status: 'PUBLISHED', created_at: new Date().toISOString(), questions: [{ id: 'q1', form_id: 'public-survey', question_text: 'How are you feeling about your progress?', question_type: 'MULTIPLE_CHOICE', required: true, options: ['Very confident', 'Making progress', 'I need more support'], order: 1 }, { id: 'q2', form_id: 'public-survey', question_text: 'Tell us anything you would like the team to know.', question_type: 'LONG_TEXT', required: false, options: [], order: 2 }] };

export function PublicSurveyPage() {
  const { formId } = useParams();
  const [form, setForm] = useState<Form>(fallbackForm);
  const [answers, setAnswers] = useState<Record<string, any>>({});
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { if (formId) api.getForm(formId).then(setForm).catch(() => setForm(fallbackForm)); }, [formId]);
  const questions = form.questions || [];
  const completed = questions.filter((question) => answers[question.id]).length;
  const update = (id: string, value: any) => setAnswers((current) => ({ ...current, [id]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { await api.submitFormResponse(form.id, { beneficiary_id: 'public-response', beneficiary_name: 'Public participant', answers }); setSubmitted(true); } catch { setError('We could not submit your response. Please check the required fields and try again.'); } };
  if (submitted) return <div className="survey-page"><div className="survey-card survey-card--success"><CheckCircle2 className="auth-success-icon" /><span className="public-kicker">Response received</span><h1>Thank you for checking in.</h1><p>Your response has been securely sent to the programme team.</p><Link to="/" className="public-button public-button--primary">Return home</Link></div></div>;
  return <div className="survey-page"><header className="survey-header"><Link to="/" className="public-brand"><span className="public-brand__mark">VG</span><span><strong>Voice of a Girl</strong><small>Participant survey</small></span></Link><span className="survey-secure"><ClipboardList className="h-4 w-4" /> No login required</span></header><main className="survey-card"><span className="public-kicker">{form.form_type} survey</span><h1>{form.title}</h1><p>{form.description}</p><div className="survey-progress"><div><span>{completed} of {questions.length} answered</span><strong>{questions.length ? Math.round((completed / questions.length) * 100) : 0}%</strong></div><div className="survey-progress__track"><span style={{ width: `${questions.length ? (completed / questions.length) * 100 : 0}%` }} /></div></div>{error && <div className="auth-alert auth-alert--error">{error}</div>}<form onSubmit={submit} className="survey-form">{questions.map((question, index) => <fieldset key={question.id}><legend><span>{index + 1}</span>{question.question_text}{question.required && <b>*</b>}</legend>{question.question_type === 'LONG_TEXT' ? <textarea required={question.required} rows={4} value={answers[question.id] || ''} onChange={(e) => update(question.id, e.target.value)} /> : question.question_type === 'NUMBER' ? <input required={question.required} type="number" value={answers[question.id] || ''} onChange={(e) => update(question.id, e.target.value)} /> : question.question_type === 'DATE' ? <input required={question.required} type="date" value={answers[question.id] || ''} onChange={(e) => update(question.id, e.target.value)} /> : question.question_type === 'YES_NO' || question.question_type === 'MULTIPLE_CHOICE' ? <div className="survey-options">{(question.options?.length ? question.options : ['Yes', 'No']).map((option) => <label key={option}><input required={question.required} type="radio" name={question.id} value={option} checked={answers[question.id] === option} onChange={(e) => update(question.id, e.target.value)} />{option}</label>)}</div> : <input required={question.required} value={answers[question.id] || ''} onChange={(e) => update(question.id, e.target.value)} />}</fieldset>)}<button className="public-button public-button--primary auth-submit" type="submit">Submit response <Send className="h-4 w-4" /></button></form></main></div>;
}
