# Generated by Django 5.2 on 2026-09-06

import datetime
import random

from django.db import migrations
from django.utils import timezone

from apps.accounts.models import CustomUser
from apps.monitoring.models import Challenge
from apps.organisations.models import Organisation
from apps.participants.models import Participant
from apps.programmes.models import (
    Programme,
    ProgrammeEnrollment,
    ProgrammeKPI,
    ProgrammeObjective,
)
from apps.surveys.models import Answer, Question, Survey, SurveyAssignment, SurveyResponse


def seed_demo(apps, schema_editor):
    ADMIN_EMAIL = "admin@voiceofagirl.org"
    ADMIN_PASSWORD = "Admin@2026!"
    ORG_EMAIL = "org@brightfuture.org"
    ORG_PASSWORD = "Org@2026!"
    ORG2_EMAIL = "org@risinghope.org"
    ORG2_PASSWORD = "Org@2026!"

    PARTICIPANTS = [
        ("Sarah Nakato", 2004, "Kampala", "SECONDARY_O_LEVEL", ["Basic computer"], "Tailoring", "UNEMPLOYED"),
        ("Grace Auma", 2003, "Gulu", "SECONDARY_A_LEVEL", ["Baking"], "Catering business", "UNEMPLOYED"),
        ("Mary Akello", 2005, "Lira", "PRIMARY", [], "Hairdressing", "UNEMPLOYED"),
        ("Joan Nabukenya", 2002, "Kampala", "VOCATIONAL", ["Sewing"], "Fashion design", "SELF_EMPLOYED"),
        ("Esther Kirabo", 2004, "Jinja", "SECONDARY_O_LEVEL", ["Mobile money"], "Accounting", "UNEMPLOYED"),
        ("Rebecca Atim", 2003, "Soroti", "DIPLOMA", ["Data entry"], "IT support", "PART_TIME"),
        ("Patricia Nabirye", 2005, "Masaka", "SECONDARY_O_LEVEL", ["Beadwork"], "Jewellery business", "STUDENT"),
        ("Christine Adong", 2002, "Kitgum", "SECONDARY_A_LEVEL", ["Farming"], "Agribusiness", "SELF_EMPLOYED"),
        ("Betty Namusoke", 2004, "Mbarara", "PRIMARY", [], "Shop keeping", "UNEMPLOYED"),
        ("Doreen Achieng", 2003, "Arua", "SECONDARY_O_LEVEL", ["Phone repair"], "Electronics", "UNEMPLOYED"),
        ("Fiona Kabugho", 2005, "Kasese", "SECONDARY_O_LEVEL", ["Photography"], "Media", "STUDENT"),
        ("Zainab Nabbosa", 2002, "Kampala", "VOCATIONAL", ["Catering"], "Restaurant", "PART_TIME"),
    ]

    INDICATORS = {
        "Are you currently employed or running a business?": (
            "YES_NO",
            [],
            ["No", "No", "Yes", "No", "No", "No", "No", "Yes", "No", "No", "No", "Yes"],
            ["Yes", "Yes", "No", "Yes", "Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes"],
        ),
        "How many hours per week do you spend on income-generating activities?": (
            "NUMBER",
            [],
            [0, 2, 0, 10, 3, 8, 0, 12, 0, 4, 0, 9],
            [15, 12, 4, 20, 14, 8, 10, 22, 5, 16, 6, 18],
        ),
        "Rate your confidence in using digital tools (1 = low, 5 = high)": (
            "RATING",
            [],
            [1, 2, 1, 3, 2, 3, 1, 3, 1, 2, 1, 3],
            [4, 4, 3, 5, 4, 4, 4, 5, 3, 4, 3, 5],
        ),
    }

    CHALLENGES = [
        ("TRANSPORT", "Sarah cannot afford daily transport to the training centre.", "RESOLVED"),
        ("FINANCIAL", "Grace lacks startup capital for her baking business.", "IN_PROGRESS"),
        ("ATTENDANCE", "Mary misses sessions during planting season.", "OPEN"),
        ("MATERIALS", "Training centre has only 5 laptops for 12 learners.", "OPEN"),
        ("TRANSPORT", "Fuel costs increased; pickup service is unsustainable.", "IN_PROGRESS"),
    ]

    if not CustomUser.objects.filter(email=ADMIN_EMAIL).exists():
        CustomUser.objects.create_superuser(
            email=ADMIN_EMAIL,
            password=ADMIN_PASSWORD,
            first_name="Platform",
            last_name="Admin",
        )

    org, _ = Organisation.objects.get_or_create(
        name="Bright Future Girls Initiative",
        defaults={
            "organisation_type": "NGO",
            "contact_person": "Programme Coordinator",
            "email": ORG_EMAIL,
            "phone_number": "+256700000000",
            "address": "Plot 12, Kampala Road",
            "district": "Kampala",
            "status": Organisation.Status.ACTIVE,
        },
    )
    org_user = CustomUser.objects.filter(email=ORG_EMAIL).first()
    if not org_user:
        org_user = CustomUser.objects.create_user(
            email=ORG_EMAIL,
            password=ORG_PASSWORD,
            first_name="Programme",
            last_name="Coordinator",
            role=CustomUser.Role.ORGANISATION,
            organisation=org,
            is_verified=True,
        )

    Organisation.objects.get_or_create(
        name="Rising Hope Foundation",
        defaults={
            "organisation_type": "NGO",
            "contact_person": "Programme Coordinator",
            "email": ORG2_EMAIL,
            "phone_number": "+256700000001",
            "address": "Plot 34, Gulu Road",
            "district": "Gulu",
            "status": Organisation.Status.ACTIVE,
        },
    )
    if not CustomUser.objects.filter(email=ORG2_EMAIL).exists():
        org2 = Organisation.objects.get(name="Rising Hope Foundation")
        CustomUser.objects.create_user(
            email=ORG2_EMAIL,
            password=ORG2_PASSWORD,
            first_name="Programme",
            last_name="Coordinator",
            role=CustomUser.Role.ORGANISATION,
            organisation=org2,
            is_verified=True,
        )

    participants = []
    for name, birth_year, district, education, skills, goal, employment in PARTICIPANTS:
        participant, _ = Participant.objects.get_or_create(
            full_name=name,
            organisation=org,
            defaults={
                "date_of_birth": datetime.date(birth_year, 6, 15),
                "gender": Participant.Gender.FEMALE,
                "phone_number": f"+25677{random.randint(1000000, 9999999)}",
                "district": district,
                "region": "Central" if district == "Kampala" else "Northern",
                "education_level": education,
                "skills": skills,
                "interests": ["Entrepreneurship", "Digital skills"],
                "career_goals": goal,
                "employment_status": employment,
                "registration_source": "Voice of a Girl community form",
                "verification_status": Participant.VerificationStatus.VERIFIED,
            },
        )
        participants.append(participant)

    today = timezone.now().date()
    programme, _ = Programme.objects.get_or_create(
        title="Digital Skills for Girls",
        organisation=org,
        defaults={
            "description": (
                "A six-month programme equipping out-of-school girls with digital "
                "literacy, online freelancing and entrepreneurship skills."
            ),
            "category": "Digital Inclusion",
            "location": "Kampala, Uganda",
            "start_date": today - datetime.timedelta(days=120),
            "end_date": today + datetime.timedelta(days=60),
            "status": Programme.Status.ACTIVE,
            "target_participants": 15,
            "created_by": org_user,
        },
    )

    ProgrammeObjective.objects.get_or_create(
        programme=programme,
        title="Train 15 girls in basic digital literacy",
        defaults={"order": 0},
    )
    ProgrammeObjective.objects.get_or_create(
        programme=programme,
        title="Connect at least 50% of graduates to income opportunities",
        defaults={"order": 1},
    )
    ProgrammeKPI.objects.get_or_create(
        programme=programme,
        name="Girls trained",
        defaults={
            "category": ProgrammeKPI.Category.OUTPUT,
            "unit": "participants",
            "target_value": 15,
            "current_value": 12,
            "baseline_value": 0,
        },
    )
    ProgrammeKPI.objects.get_or_create(
        programme=programme,
        name="Employment rate",
        defaults={
            "category": ProgrammeKPI.Category.OUTCOME,
            "unit": "%",
            "target_value": 50,
            "current_value": 43,
            "baseline_value": 21,
            "measurement_frequency": "Per cohort",
        },
    )

    statuses = (
        [ProgrammeEnrollment.Status.ACTIVE] * 8
        + [ProgrammeEnrollment.Status.COMPLETED] * 2
        + [ProgrammeEnrollment.Status.DROPPED_OUT] * 2
    )
    for participant, status in zip(participants, statuses):
        ProgrammeEnrollment.objects.get_or_create(
            programme=programme,
            participant=participant,
            defaults={
                "status": status,
                "progress": 100.0 if status == "COMPLETED" else round(random.uniform(40, 85), 1),
                "completed_at": timezone.now() if status == "COMPLETED" else None,
                "outcome_notes": (
                    "Completed all modules and submitted final project."
                    if status == "COMPLETED"
                    else ""
                ),
            },
        )

    for survey_type, title, description, values_index in (
        (
            Survey.SurveyType.BASELINE,
            "Digital Skills Baseline Survey",
            "Collected before training begins.",
            2,
        ),
        (
            Survey.SurveyType.ENDLINE,
            "Digital Skills Endline Survey",
            "Collected after training completion.",
            3,
        ),
    ):
        survey, _ = Survey.objects.get_or_create(
            title=title,
            organisation=org,
            defaults={
                "description": description,
                "survey_type": survey_type,
                "programme": programme,
                "status": Survey.Status.PUBLISHED,
                "created_by": org_user,
            },
        )
        if not survey.questions.exists():
            for order, (text, spec) in enumerate(INDICATORS.items()):
                Question.objects.create(
                    survey=survey,
                    question_text=text,
                    question_type=spec[0],
                    options=spec[1],
                    order=order,
                )

        if survey.responses.filter(submitted=True).exists():
            continue
        questions = list(survey.questions.order_by("order"))
        for index, participant in enumerate(participants):
            response, _ = SurveyResponse.objects.get_or_create(
                survey=survey,
                participant=participant,
                organisation=org,
                defaults={},
            )
            SurveyAssignment.objects.get_or_create(
                survey=survey, participant=participant
            )
            for question in questions:
                values = INDICATORS[question.question_text][values_index]
                Answer.objects.create(
                    response=response,
                    question=question,
                    value=values[index],
                )
            response.submitted = True
            response.submitted_at = timezone.now()
            response.save()

    endline = Survey.objects.get(title="Digital Skills Endline Survey", organisation=org)
    if not endline.responses.filter(submitted=False).exists():
        SurveyResponse.objects.create(survey=endline, organisation=org)

    if not Challenge.objects.filter(organisation=org).exists():
        now = timezone.now()
        for index, (category, description, status) in enumerate(CHALLENGES):
            Challenge.objects.create(
                organisation=org,
                programme=programme,
                participant=participants[index % len(participants)],
                category=category,
                description=description,
                status=status,
                date_reported=now - datetime.timedelta(days=30 - index * 3),
                date_resolved=now - datetime.timedelta(days=10) if status == "RESOLVED" else None,
                resolution_notes="Provided transport stipend." if status == "RESOLVED" else "",
                reported_by=org_user,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("monitoring", "0001_initial"),
        ("organisations", "0001_initial"),
        ("participants", "0001_initial"),
        ("programmes", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_demo, migrations.RunPython.noop),
    ]
