# Generated by Django 5.2.17 on 2026-09-05 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impact', '0002_initial'),
        ('organisations', '0001_initial'),
        ('programmes', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('GENERAL', 'General Impact Report'), ('PROGRAMME', 'Programme Report'), ('SURVEY', 'Survey Report'), ('IMPACT', 'Impact Report'), ('KPI', 'KPI Report'), ('PROJECT', 'Impact Project Report')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='GENERATING', max_length=20)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('impact_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='impact.impactproject')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='programmes.programme')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='surveys.survey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='reports_rep_organis_180f3d_idx')],
            },
        ),
    ]
