# Generated by Django 5.2.14 on 2026-09-06 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                        ],
                        default="FEMALE",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="Uganda", max_length=100)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("NONE", "No Formal Education"),
                            ("PRIMARY", "Primary Education"),
                            ("SECONDARY_O_LEVEL", "Secondary (O-Level)"),
                            ("SECONDARY_A_LEVEL", "Secondary (A-Level)"),
                            ("VOCATIONAL", "Vocational / Certificate"),
                            ("DIPLOMA", "Diploma"),
                            ("BACHELORS", "Bachelors Degree"),
                            ("POSTGRADUATE", "Postgraduate"),
                            ("OTHER", "Other / Informal"),
                        ],
                        default="SECONDARY_O_LEVEL",
                        max_length=30,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("career_goals", models.TextField(blank=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("UNEMPLOYED", "Unemployed"),
                            ("STUDENT", "Student"),
                            ("SELF_EMPLOYED", "Self-Employed / Entrepreneur"),
                            ("PART_TIME", "Part-time Employment"),
                            ("FULL_TIME", "Full-time Employment"),
                            ("INTERN", "Intern / Apprentice"),
                        ],
                        default="UNEMPLOYED",
                        max_length=30,
                    ),
                ),
                ("registration_source", models.CharField(blank=True, max_length=100)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
